---
- name: Validate custom site has required values.
  ansible.builtin.assert:
    that:
      - nginx_custom.name is defined
      - nginx_custom.name | length > 1
    quiet: true

- name: Create the loadbalancer site.
  ansible.builtin.template:
    dest: "/etc/nginx/sites-available/{{ nginx_custom.name }}"
    src: custom-site.j2
    mode: "0644"
  notify: Reload nginx

- name: Enable the loadbalancer site.
  ansible.builtin.file:
    dest: "/etc/nginx/sites-enabled/{{ nginx_custom.name }}"
    src: "../sites-available/{{ nginx_custom.name }}"
    state: link
  notify: Reload nginx
